<a href="https://colab.research.google.com/github/atakanberkyilmaz/Hafta2PandasKutuphanesi/blob/main/Hafta_2_Pandas_K%C3%BCt%C3%BCphanesi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Kütüphanesi

In [ ]:
#Liste 3.1
import pandas as pd

In [ ]:
#Liste 3.2
seri1 = pd.Series([2018,'Makine Öğrenmesi',-5.23])
print(seri1)

0                2018
1    Makine Öğrenmesi
2               -5.23
dtype: object

In [ ]:
#Liste 3.3
seri1 = pd.Series([2018,'Makine Öğrenmesi',-5.23],index=['A','B','C'])
print(seri1)
print(seri1['A'])
print(seri1[0])

A                2018
B    Makine Öğrenmesi
C               -5.23
dtype: object
2018
2018

In [ ]:
#Liste 3.4
seri1 = pd.Series([10,15,20,25,30,35])
print(seri1[2:4])

2    20
3    25
dtype: int64

In [ ]:
#Liste 3.5
notlar = {"Matematik": 70, "Bilgisayar": 90, "Elektronik": 96, "İstatistik": 55}
seri1 = pd.Series(notlar)
print(seri1)

Matematik     70
Bilgisayar    90
Elektronik    96
İstatistik    55
dtype: int64

In [ ]:
#Liste 3.6
notlar = {"Matematik": 70, "Bilgisayar": 90, "Elektronik": 96, "İstatistik": 55}
seri1 = pd.Series(notlar)
print('Fizik' in seri1)

False

In [ ]:
#Liste 3.7
notlar = {"Matematik": 70, "Bilgisayar": 90, "Elektronik": 96, "İstatistik": 55}
seri1 = pd.Series(notlar)
print(seri1*1.05)
import numpy as np
np.sqrt(seri1)

Matematik      73.50
Bilgisayar     94.50
Elektronik    100.80
İstatistik     57.75
dtype: float64

Matematik     8.366600
Bilgisayar    9.486833
Elektronik    9.797959
İstatistik    7.416198
dtype: float64

In [ ]:
#Liste 3.8
seri1 = pd.Series([10,15,20,25,30,35])
print(seri1[seri1>22])

3    25
4    30
5    35
dtype: int64

In [ ]:
#Liste 3.9
seri1 = pd.Series([10,15,20,25,25,20,10,15,45,50,20])
print(seri1.unique())
print(seri1.value_counts())

[10 15 20 25 45 50]
20    3
10    2
15    2
25    2
45    1
50    1
dtype: int64

In [ ]:
#Liste 3.10
ogrenciler_dict = {
    "okulNo": pd.Series([101, 110, 606], index=["Asel", "Betül", "Niyazi"]),
    "ortalama": pd.Series([90, 95, 97], index=["Asel", "Betül", "Niyazi"]),
    "bolum": pd.Series(['Makine Müh.','Bilgisayar Müh.','Mekatronik Müh. '], index=["Asel", "Betül", "Niyazi"]),
    "dogumTarihi": pd.Series([2000,2000,1998], index=["Asel", "Betül", "Niyazi"]),
}
tablo = pd.DataFrame(ogrenciler_dict)
print(tablo)
print(tablo[tablo["ortalama"] < 93])

        okulNo  ortalama             bolum  dogumTarihi
Asel       101        90       Makine Müh.         2000
Betül      110        95   Bilgisayar Müh.         2000
Niyazi     606        97  Mekatronik Müh.          1998
      okulNo  ortalama        bolum  dogumTarihi
Asel     101        90  Makine Müh.         2000

In [ ]:
#Liste 3.11
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Colab\ Notebooks
veriseti = pd.read_excel('EnergyStarScore', 'Sayfa1')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Colab Notebooks

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
#Liste 3.12
veriseti.info()
veriseti.sample(3)
veriseti.sample(frac=0.05)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Bina Adı   950 non-null    object
 1   Bina Tipi  936 non-null    object
 2   BA         936 non-null    float64
 3   BEKY       893 non-null    float64
 4   SGE        934 non-null    float64
 5   SGY        928 non-null    float64
 6   BTE        896 non-null    float64
 7   ESS        736 non-null    float64
dtypes: float64(6), object(2)
memory usage: 59.5+ KB

,Bina Adı,Bina Tipi,BA,BEKY,SGE,SGY,BTE,ESS
412,MISSION,K-12 School,64400.0,30.400000,109.800000,1.700000,1.959026e+06,100.0
147,STP LLC,Retail Store,171918.0,NaN,NaN,NaN,NaN,NaN
121,660 Washington,Multifamily Housing,711442.0,74.300000,3280.300000,5.400000,4.545336e+07,25.0
740,HBS Rock Center,Office,27782.0,94.300000,206.200000,7.400000,2.618679e+06,65.0
686,Leventhal House: 40 Wallingford Rd.,Multifamily Housing,158387.0,91.300000,957.000000,6.000000,1.445392e+07,33.0
353,Granite Harrison Court,Multifamily Housing,79825.0,66.800000,463.800000,5.800000,5.334580e+06,NaN
216,Harvard SPH 1,Laboratory,164789.0,230.300000,2720.200000,16.500000,3.795427e+07,NaN
316,The Colonnade Hotel,Hotel,276439.0,135.400000,2475.900000,9.000000,3.744143e+07,54.0
718,Stony Brook Village,Multifamily Housing,62500.0,98.400000,389.200000,6.200000,6.148179e+06,42.0
881,Windsor Place Condominium,Multifamily Housing,120295.0,75.300000,625.600000,5.200000,9.061630e+06,69.0
521,Carson Tower,Multifamily Housing,116876.0,166.800000,1035.200000,8.900000,1.948984e+07,NaN
79,3 PO Square,Office,65120.0,131.600000,611.400000,9.400000,8.567654e+06,38.0
185,PHS-MGH-CRP 165,Medical Office,157187.0,73.300000,1114.400000,7.100000,1.151896e+07,49.0
364,Southampton Street,Office,44719.0,11.400000,49.500000,1.100000,5.112541e+05,100.0
781,51 Melcher,Office,99000.0,61.500000,512.200000,5.200000,6.087768e+06,86.0
941,504 FANEUIL,Multifamily Housing,216568.0,182.394857,3049.651047,14.081725,3.950089e+07,NaN
651,HRE - 1380 Soldiers Field Rd,Office,104922.0,109.400000,689.800000,9.000000,8.420092e+06,41.0
921,249 TORRE UNIDAD,Multifamily Housing,109724.0,96.052417,888.142004,8.094328,1.053926e+07,NaN
733,HBS Loeb House,Office,6067.0,54.400000,25.000000,4.100000,3.300554e+05,94.0
57,Union Wharf Condominiums,Multifamily Housing,250000.0,17.800000,332.700000,1.300000,4.443207e+06,NaN
100,Mission Park Apartments,Multifamily Housing,786880.0,94.600000,4649.200000,5.900000,7.445006e+07,45.0
388,HERNANDEZ,K-12 School,64313.0,65.700000,246.000000,3.800000,4.222750e+06,91.0
826,"1330 Boylston Street Properties, LLC",Multifamily Housing,480485.0,64.200000,1725.700000,4.800000,2.320212e+07,NaN
417,New England Baptist Hospital,Hospital (General Medical & Surgical),425548.0,282.100000,8657.500000,20.300000,1.200295e+08,9.0
696,WGBH Educational Foundation - 1 Guest,Office,278871.0,83.700000,1863.200000,6.700000,2.333835e+07,79.0
92,Commercial Wharf East Condominium,Multifamily Housing,121932.0,2.400000,27.900000,0.200000,2.903048e+05,NaN
508,Economy Plumbing && Heating Supply Co,Distribution Center,65000.0,NaN,0.000000,0.000000,NaN,NaN
284,Brookline Bancorp,Financial Office,70346.0,123.500000,697.100000,9.900000,8.686029e+06,39.0
663,25833-Brighton/Lincoln ST,Non-Refrigerated Warehouse,113000.0,8.900000,78.300000,0.700000,1.002954e+06,99.0
584,Brewery Lofts,Multifamily Housing,86900.0,62.000000,370.900000,4.300000,5.385128e+06,73.0
70,2 Atlantic,Office,128524.0,145.800000,786.700000,11.600000,9.917984e+06,23.0
488,Catherine Clark: Catherine Clark,Multifamily Housing,74185.0,90.000000,445.000000,6.000000,6.678716e+06,38.0
568,"Mishawum Park: Bldgs 17, 18, and 20",Multifamily Housing,30425.0,55.400000,102.500000,3.400000,1.686404e+06,98.0
333,500 Harrison Ave,Office,145000.0,10.000000,84.900000,0.600000,1.443129e+06,100.0
492,Columbia West: 392 Columbia Rd,Multifamily Housing,41632.0,75.600000,213.200000,5.100000,3.146714e+06,58.0
814,World Trade Center West,Office,551185.0,72.000000,3837.600000,7.000000,3.966708e+07,70.0
482,#2679 South Bay/Boston,Retail Store,132000.0,63.800000,676.900000,5.100000,8.418749e+06,77.0
831,25 Buick Street,Office,122472.0,NaN,0.000000,0.000000,NaN,NaN
297,Garrison Square,Multifamily Housing,115806.0,57.300000,641.800000,5.500000,6.634252e+06,NaN
449,CLEVELAND NEW,K-12 School,91562.0,109.200000,582.600000,6.400000,9.997104e+06,46.0
292,Exeter Theatre Corporation,Mixed Use Property,46025.0,54.900000,240.000000,5.200000,2.528384e+06,NaN
706,Fairview Cemetery Administration Building,Office,2400.0,137.200000,25.300000,10.500000,3.293504e+05,NaN
659,10/20 Guest Street,Office,218104.0,77.600000,1603.400000,7.400000,1.691804e+07,NaN
250,Susan Bailis Assisted Living,Senior Care Community,59999.0,NaN,NaN,NaN,NaN,NaN
707,Georgetowne Homes I,Multifamily Housing,1540954.0,21.700000,1845.600000,1.200000,3.344521e+07,100.0
609,BATES,K-12 School,27936.0,72.400000,122.100000,4.400000,2.021344e+06,88.0
207,"Cohen Wing Basement, Boston Symphony Orchestra",Office,20000.0,0.900000,0.900000,0.000000,1.754050e+04,NaN
144,Residences of 210 South Street Condominium,Multifamily Housing,87964.0,53.300000,370.800000,4.200000,4.685390e+06,34.0

In [ ]:
#Liste 3.13
veriseti.head(3)
veriseti[['Bina Adı','ESS']].head(7)

                                Bina Adı    ESS
0                Commonwealth Apartments   69.0
1                River House Condo Trust  100.0
2  Tremont Residential (Grandview Condo)   75.0
3                   44 School Street LLC  100.0
4                            101 Tremont    NaN
5                             18 Tremont    1.0
6                       20 City Hall Ave   69.0

In [ ]:
#Liste 3.14
veriseti[veriseti.ESS>=95].head(3)
veriseti[(veriseti.ESS>=60)&(veriseti.ESS<=70)].head(1)
veriseti.tail(2)
veriseti[200:301]

In [ ]:
#Liste 3.15
veriseti.corr()

In [ ]:
#Liste 3.16
import seaborn as sb
sb.heatmap(veriseti.corr(),annot=True,fmt = ".2f", cmap = "coolwarm",linewidths= 2.2)